services:
  # MongoDB
  mongodb:
    image: mongo:7.0
    container_name: mongoose-ai-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mongoose_ai
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3

  # mongoose-ai development environment
  mongoose-ai:
    build: .
    container_name: mongoose-ai-runner
    environment:
      MONGODB_URI: mongodb://mongodb:27017/mongoose_ai
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data: